var app = require("grnai-vis-phenotypes");

var elements = {
  nodes: [
    { data: { id: 'mrup', name: "Muscles rounded up" }, classes: "phenotype" },
    { data: { id: 'mspread', name: "Muscles spread" }, classes: "phenotype" },
    { data: { id: 'amlstr', name: "Actin and myosin filaments lack striation" }, classes: "phenotype" },
    { data: { id: 'alstr', name: "Actin filaments lack striation" }, classes: "phenotype" },
    { data: { id: 'mstr', name: "Myosin filaments striated" }, classes: "phenotype" },
    { data: { id: 'msmyo', name: "Muscles with short and/or thin myofibrils" }, classes: "phenotype" },
    { data: { id: 'mew', mappedId: "32275", geneId: "FBgn0004456", reagentId: ["DRSC18971", "DRSC20352", "DRSC35847"], scoreType: "Percentage of muscles with a given phenotype", cutoff: "Severe: > 80 %; medium: ~ 50 %" }, classes: "gene" },
    { data: { id: 'Fit1' }, classes: "gene" },
    { data: { id: 'Lasp' }, classes: "gene" },
    { data: { id: 'Fit2' }, classes: "gene" },
    { data: { id: 'CG152' }, classes: "gene" },
    { data: { id: 'ldh' }, classes: "gene" },
    { data: { id: 'up' }, classes: "gene" },
    { data: { id: 'wupA' }, classes: "gene" },
    { data: { id: 'mhc' }, classes: "gene" },
    { data: { id: 'Prm' }, classes: "gene" },
    { data: { id: 'CalpB' }, classes: "gene" },
    { data: { id: 'polo' }, classes: "gene" },
    { data: { id: 'Mlc2' }, classes: "gene" },
    { data: { id: 'Tmod' }, classes: "gene" },
    { data: { id: 'bt' }, classes: "gene" },
    { data: { id: 'Rya-r44F' }, classes: "gene" },

    { data: { id: 'Actn' }, classes: "gene" },
    { data: { id: 'CG3457' }, classes: "gene" },
    { data: { id: 'lvh' }, classes: "gene" },
    { data: { id: 'sqh' }, classes: "gene" },
    { data: { id: 'mtm' }, classes: "gene" },
    { data: { id: 'tafazzin' }, classes: "gene" },
    { data: { id: 'CG15105' }, classes: "gene" },
    { data: { id: 'CG6640' }, classes: "gene" },
    { data: { id: 'Prosbeta2' }, classes: "gene" },
    { data: { id: 'Taf4' }, classes: "gene" },
    { data: { id: 'CG5027' }, classes: "gene" },
    { data: { id: 'Pros26' }, classes: "gene" },
    { data: { id: 'CG8789' }, classes: "gene" },
    { data: { id: 'Rpn1' }, classes: "gene" },
    { data: { id: 'CG6020' }, classes: "gene" },
    { data: { id: 'CG6014' }, classes: "gene" },
    { data: { id: 'abs' }, classes: "gene" },
    { data: { id: 'CG9779' }, classes: "gene" },
    { data: { id: 'CG9776' }, classes: "gene" },
    { data: { id: 'CG14648' }, classes: "gene" },
    { data: { id: 'atms' }, classes: "gene" },
    { data: { id: 'Nf1' }, classes: "gene" },
    { data: { id: 'Rpn2' }, classes: "gene" },
    { data: { id: 'Mgat2' }, classes: "gene" },
    { data: { id: 'PH4alphaNE1' }, classes: "gene" },
    { data: { id: 'CG1544' }, classes: "gene" },
    { data: { id: 'pygo' }, classes: "gene" },
    { data: { id: 'CG1890' }, classes: "gene" },
    { data: { id: 'RhoGAP100F' }, classes: "gene" },
    { data: { id: 'sls' }, classes: "gene" },
    { data: { id: 'deltaCOP' }, classes: "gene" },
    { data: { id: 'elF-4E' }, classes: "gene" },
    { data: { id: 'CG31523' }, classes: "gene" },

    { data: { id: 'Vinc' }, classes: "gene" },
    { data: { id: 'crn' }, classes: "gene" },
    { data: { id: 'CG8636' }, classes: "gene" },
    { data: { id: 'Act5C' }, classes: "gene" },
    { data: { id: 'Act42A' }, classes: "gene" },
    { data: { id: 'Act57B' }, classes: "gene" },
    { data: { id: 'Trn' }, classes: "gene" },
    { data: { id: 'RpS9' }, classes: "gene" },
    { data: { id: 'Taf2' }, classes: "gene" },
    { data: { id: 'RpS12' }, classes: "gene" },
    { data: { id: 'CG5931' }, classes: "gene" },
    { data: { id: 'CG8743' }, classes: "gene" },
    { data: { id: 'Ac76E' }, classes: "gene" },
    { data: { id: 'CG31374' }, classes: "gene" },
    { data: { id: 'RpL4' }, classes: "gene" },
    { data: { id: 'Act87E' }, classes: "gene" }
  ],
  edges: [
    { data: { source: 'mrup', target: 'mew' } },
    { data: { source: 'mrup', target: 'Fit1' } },
    { data: { source: 'mrup', target: 'Lasp' } },
    { data: { source: 'mrup', target: 'Fit2' } },
    { data: { source: 'mrup', target: 'CG152' } },
    { data: { source: 'mrup', target: 'ldh' } },
    { data: { source: 'mspread', target: 'up' } },
    { data: { source: 'mspread', target: 'wupA' } },
    { data: { source: 'mspread', target: 'mhc' } },
    { data: { source: 'mspread', target: 'Prm' } },
    { data: { source: 'mspread', target: 'CalpB' } },
    { data: { source: 'mspread', target: 'polo' } },
    { data: { source: 'mspread', target: 'Mlc2' } },
    { data: { source: 'mspread', target: 'Tmod' } },
    { data: { source: 'mspread', target: 'bt' } },
    { data: { source: 'mspread', target: 'Rya-r44F' } },
    { data: { source: 'amlstr', target: 'up' } },
    { data: { source: 'amlstr', target: 'wupA' } },
    { data: { source: 'amlstr', target: 'mhc' } },
    { data: { source: 'amlstr', target: 'Prm' } },
    { data: { source: 'amlstr', target: 'CalpB' } },
    { data: { source: 'amlstr', target: 'polo' } },
    { data: { source: 'amlstr', target: 'Mlc2' } },
    { data: { source: 'amlstr', target: 'Tmod' } },
    { data: { source: 'amlstr', target: 'bt' } },
    { data: { source: 'amlstr', target: 'Rya-r44F' } },

    { data: { source: 'mspread', target: 'Actn' } },
    { data: { source: 'mspread', target: 'CG3457' } },
    { data: { source: 'mspread', target: 'lvh' } },
    { data: { source: 'mspread', target: 'sqh' } },
    { data: { source: 'mspread', target: 'mtm' } },
    { data: { source: 'mspread', target: 'tafazzin' } },
    { data: { source: 'mspread', target: 'CG15105' } },
    { data: { source: 'mspread', target: 'CG6640' } },
    { data: { source: 'mspread', target: 'Prosbeta2' } },
    { data: { source: 'mspread', target: 'Taf4' } },
    { data: { source: 'mspread', target: 'CG5027' } },
    { data: { source: 'mspread', target: 'Pros26' } },
    { data: { source: 'mspread', target: 'CG8789' } },
    { data: { source: 'mspread', target: 'Rpn1' } },
    { data: { source: 'mspread', target: 'CG6020' } },
    { data: { source: 'mspread', target: 'CG6014' } },
    { data: { source: 'mspread', target: 'abs' } },
    { data: { source: 'mspread', target: 'CG9779' } },
    { data: { source: 'mspread', target: 'CG9776' } },
    { data: { source: 'mspread', target: 'CG14648' } },
    { data: { source: 'mspread', target: 'atms' } },
    { data: { source: 'mspread', target: 'Nf1' } },
    { data: { source: 'mspread', target: 'Rpn2' } },
    { data: { source: 'mspread', target: 'Mgat2' } },
    { data: { source: 'mspread', target: 'PH4alphaNE1' } },
    { data: { source: 'mspread', target: 'CG1544' } },
    { data: { source: 'mspread', target: 'pygo' } },
    { data: { source: 'mspread', target: 'CG1890' } },
    { data: { source: 'mspread', target: 'RhoGAP100F' } },
    { data: { source: 'mspread', target: 'sls' } },
    { data: { source: 'mspread', target: 'deltaCOP' } },
    { data: { source: 'mspread', target: 'elF-4E' } },
    { data: { source: 'mspread', target: 'CG31523' } },

    { data: { source: 'mstr', target: 'Actn' } },
    { data: { source: 'mstr', target: 'CG3457' } },
    { data: { source: 'mstr', target: 'lvh' } },
    { data: { source: 'mstr', target: 'sqh' } },
    { data: { source: 'mstr', target: 'mtm' } },
    { data: { source: 'mstr', target: 'tafazzin' } },
    { data: { source: 'mstr', target: 'CG15105' } },
    { data: { source: 'mstr', target: 'CG6640' } },
    { data: { source: 'mstr', target: 'Prosbeta2' } },
    { data: { source: 'mstr', target: 'Taf4' } },
    { data: { source: 'mstr', target: 'CG5027' } },
    { data: { source: 'mstr', target: 'Pros26' } },
    { data: { source: 'mstr', target: 'CG8789' } },
    { data: { source: 'mstr', target: 'Rpn1' } },
    { data: { source: 'mstr', target: 'CG6020' } },
    { data: { source: 'mstr', target: 'CG6014' } },
    { data: { source: 'mstr', target: 'abs' } },
    { data: { source: 'mstr', target: 'CG9779' } },
    { data: { source: 'mstr', target: 'CG9776' } },
    { data: { source: 'mstr', target: 'CG14648' } },
    { data: { source: 'mstr', target: 'atms' } },
    { data: { source: 'mstr', target: 'Nf1' } },
    { data: { source: 'mstr', target: 'Rpn2' } },
    { data: { source: 'mstr', target: 'Mgat2' } },
    { data: { source: 'mstr', target: 'PH4alphaNE1' } },
    { data: { source: 'mstr', target: 'CG1544' } },
    { data: { source: 'mstr', target: 'pygo' } },
    { data: { source: 'mstr', target: 'CG1890' } },
    { data: { source: 'mstr', target: 'RhoGAP100F' } },
    { data: { source: 'mstr', target: 'sls' } },
    { data: { source: 'mstr', target: 'deltaCOP' } },
    { data: { source: 'mstr', target: 'elF-4E' } },
    { data: { source: 'mstr', target: 'CG31523' } },

    { data: { source: 'alstr', target: 'Actn' } },
    { data: { source: 'alstr', target: 'CG3457' } },
    { data: { source: 'alstr', target: 'lvh' } },
    { data: { source: 'alstr', target: 'sqh' } },
    { data: { source: 'alstr', target: 'mtm' } },
    { data: { source: 'alstr', target: 'tafazzin' } },
    { data: { source: 'alstr', target: 'CG15105' } },
    { data: { source: 'alstr', target: 'CG6640' } },
    { data: { source: 'alstr', target: 'Prosbeta2' } },
    { data: { source: 'alstr', target: 'Taf4' } },
    { data: { source: 'alstr', target: 'CG5027' } },
    { data: { source: 'alstr', target: 'Pros26' } },
    { data: { source: 'alstr', target: 'CG8789' } },
    { data: { source: 'alstr', target: 'Rpn1' } },
    { data: { source: 'alstr', target: 'CG6020' } },
    { data: { source: 'alstr', target: 'CG6014' } },
    { data: { source: 'alstr', target: 'abs' } },
    { data: { source: 'alstr', target: 'CG9779' } },
    { data: { source: 'alstr', target: 'CG9776' } },
    { data: { source: 'alstr', target: 'CG14648' } },
    { data: { source: 'alstr', target: 'atms' } },
    { data: { source: 'alstr', target: 'Nf1' } },
    { data: { source: 'alstr', target: 'Rpn2' } },
    { data: { source: 'alstr', target: 'Mgat2' } },
    { data: { source: 'alstr', target: 'PH4alphaNE1' } },
    { data: { source: 'alstr', target: 'CG1544' } },
    { data: { source: 'alstr', target: 'pygo' } },
    { data: { source: 'alstr', target: 'CG1890' } },
    { data: { source: 'alstr', target: 'RhoGAP100F' } },
    { data: { source: 'alstr', target: 'sls' } },
    { data: { source: 'alstr', target: 'deltaCOP' } },
    { data: { source: 'alstr', target: 'elF-4E' } },
    { data: { source: 'alstr', target: 'CG31523' } },

    { data: { source: 'msmyo', target: 'Vinc' } },
    { data: { source: 'msmyo', target: 'crn' } },
    { data: { source: 'msmyo', target: 'CG8636' } },
    { data: { source: 'msmyo', target: 'Act5C' } },
    { data: { source: 'msmyo', target: 'Act42A' } },
    { data: { source: 'msmyo', target: 'Act57B' } },
    { data: { source: 'msmyo', target: 'Trn' } },
    { data: { source: 'msmyo', target: 'RpS9' } },
    { data: { source: 'msmyo', target: 'Taf2' } },
    { data: { source: 'msmyo', target: 'RpS12' } },
    { data: { source: 'msmyo', target: 'CG5931' } },
    { data: { source: 'msmyo', target: 'CG8743' } },
    { data: { source: 'msmyo', target: 'Ac76E' } },
    { data: { source: 'msmyo', target: 'CG31374' } },
    { data: { source: 'msmyo', target: 'RpL4' } },
    { data: { source: 'msmyo', target: 'Act87E' } },
  ]
};
rootDiv.id = "rootDiv";
var instance = new app({el: rootDiv, d: elements});
